# Generated by Django 5.2.6 on 2025-09-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeslotMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('time', models.PositiveIntegerField(help_text='Enter hours')),
            ],
        ),
    ]
