# Generated by Django 5.2.6 on 2025-09-18 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amenities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.assettype')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField()),
                ('bed_type', models.CharField(choices=[('SINGLE', 'Single Bed'), ('DOUBLE', 'Double Bed'), ('KING', 'King Bed'), ('QUEEN', 'Queen Bed'), ('TWIN', 'Twin Bed')], default='SINGLE', max_length=20, verbose_name='Bed Type')),
                ('amenities', models.ManyToManyField(blank=True, to='amenities.amenity')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True, verbose_name='Room ID/Number')),
                ('floor', models.IntegerField(verbose_name='Floor Number')),
                ('bed_type', models.CharField(choices=[('SINGLE', 'Single Bed'), ('DOUBLE', 'Double Bed'), ('KING', 'King Bed'), ('QUEEN', 'Queen Bed'), ('TWIN', 'Twin Bed')], default='SINGLE', max_length=20, verbose_name='Bed Type')),
                ('single_bed', models.BooleanField(default=False)),
                ('double_bed', models.BooleanField(default=False)),
                ('extra_bed', models.BooleanField(default=False)),
                ('max_occupancy', models.PositiveIntegerField(default=1, verbose_name='Max Occupancy')),
                ('allow_pax', models.PositiveIntegerField(default=1, verbose_name='Allow Pax')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance'), ('OUT_OF_ORDER', 'Out of Order')], default='AVAILABLE', max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Description/Notes')),
                ('view', models.CharField(blank=True, choices=[('SEA', 'Sea View'), ('CITY', 'City View'), ('GARDEN', 'Garden View'), ('MOUNTAIN', 'Mountain View'), ('POOL', 'Pool View'), ('COURTYARD', 'Courtyard View')], max_length=20, verbose_name='View')),
                ('rate_default', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rate (Default)')),
                ('tariff', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('slave_time', models.CharField(blank=True, max_length=100, verbose_name='Slave Time')),
                ('conditions', models.TextField(blank=True)),
                ('amenities', models.ManyToManyField(blank=True, to='amenities.amenity', verbose_name='Features/Amenities')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.asset')),
                ('asset_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.assettype')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rooms.roomtype', verbose_name='Room Type')),
            ],
        ),
    ]
