# Generated by Django 5.2.6 on 2025-09-18 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('checkin', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='checkin',
            field=models.ForeignKey(blank=True, help_text='Associated check-in', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='checkin.checkin'),
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_source',
            field=models.ForeignKey(blank=True, help_text='Reservation source (OTA, website, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.reservationsource'),
        ),
        migrations.AddField(
            model_name='roomavailabilitycache',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_cache', to='rooms.room'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('check_out_date__gt', models.F('check_in_date'))), name='check_out_after_check_in'),
        ),
        migrations.AddIndex(
            model_name='roomavailabilitycache',
            index=models.Index(fields=['date', 'is_available'], name='booking_roo_date_73d6ae_idx'),
        ),
        migrations.AddIndex(
            model_name='roomavailabilitycache',
            index=models.Index(fields=['room', 'date'], name='booking_roo_room_id_d61943_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomavailabilitycache',
            unique_together={('room', 'date')},
        ),
    ]
