# Generated by Django 5.2.6 on 2025-09-16 10:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateplan',
            name='base_rate_for_24',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Base rate for 24 Hrs', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
    ]
