# Generated by Django 5.2.6 on 2025-09-17 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_rateplan_base_rate_for_24'),
        ('timemaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateplan',
            name='time_slot',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='timemaster.timeentry'),
            preserve_default=False,
        ),
    ]
