# Generated by Django 5.2.6 on 2025-09-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_rateplan_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateplan',
            name='time_slot',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
