# Generated by Django 5.2.6 on 2025-09-18 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Status ID')),
                ('status_name', models.CharField(choices=[('CLEAN', 'Clean'), ('DIRTY', 'Dirty'), ('IN_PROGRESS', 'In Progress'), ('OUT_OF_ORDER', 'Out of Order'), ('MAINTENANCE', 'Maintenance Required'), ('INSPECTED', 'Inspected')], help_text='Housekeeping status name', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the housekeeping status', null=True)),
                ('color_code', models.CharField(default='#6c757d', help_text='Color code for status display (hex format)', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this status is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Housekeeping Status',
                'verbose_name_plural': 'Housekeeping Statuses',
                'ordering': ['status_name'],
            },
        ),
        migrations.CreateModel(
            name='HousekeepingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(help_text='Type of housekeeping task (e.g., Daily Cleaning, Deep Clean, Maintenance)', max_length=100)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Priority level of the task', max_length=10)),
                ('task_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the task', max_length=20)),
                ('assigned_to', models.CharField(blank=True, help_text='Staff member assigned to this task', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the housekeeping task', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations', null=True)),
                ('estimated_duration', models.PositiveIntegerField(default=30, help_text='Estimated duration in minutes')),
                ('actual_duration', models.PositiveIntegerField(blank=True, help_text='Actual duration taken in minutes', null=True)),
                ('scheduled_date', models.DateField(help_text='Date when the task is scheduled')),
                ('scheduled_time', models.TimeField(blank=True, help_text='Time when the task is scheduled', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the task was started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(help_text='Room for this housekeeping task', on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='rooms.room')),
                ('status', models.ForeignKey(help_text='Current housekeeping status', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='housekeeping.housekeepingstatus')),
            ],
            options={
                'verbose_name': 'Housekeeping Task',
                'verbose_name_plural': 'Housekeeping Tasks',
                'ordering': ['-scheduled_date', 'priority', 'room__room_number'],
            },
        ),
        migrations.CreateModel(
            name='HousekeepingInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector_name', models.CharField(help_text='Name of the inspector', max_length=100)),
                ('inspection_status', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('NEEDS_ATTENTION', 'Needs Attention')], help_text='Result of the inspection', max_length=20)),
                ('cleanliness_score', models.PositiveIntegerField(default=5, help_text='Cleanliness score out of 10')),
                ('issues_found', models.TextField(blank=True, help_text='Issues found during inspection', null=True)),
                ('corrective_actions', models.TextField(blank=True, help_text='Actions needed to address issues', null=True)),
                ('inspection_notes', models.TextField(blank=True, help_text='Additional inspection notes', null=True)),
                ('inspection_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of inspection')),
                ('follow_up_required', models.BooleanField(default=False, help_text='Whether follow-up inspection is required')),
                ('follow_up_date', models.DateField(blank=True, help_text='Date for follow-up inspection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(help_text='Room being inspected', on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='rooms.room')),
                ('task', models.ForeignKey(blank=True, help_text='Related housekeeping task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='housekeeping.housekeepingtask')),
            ],
            options={
                'verbose_name': 'Housekeeping Inspection',
                'verbose_name_plural': 'Housekeeping Inspections',
                'ordering': ['-inspection_date'],
            },
        ),
    ]
