# Generated by Django 5.2.6 on 2025-09-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Amenity Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('quantity_limit', models.PositiveIntegerField(blank=True, help_text='Leave blank if not applicable', null=True, verbose_name='Quantity/Limit')),
                ('is_chargeable', models.BooleanField(default=False, help_text='Check if this amenity has associated charges', verbose_name='Chargeable Amenity')),
                ('base_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Base charge for this amenity (if chargeable)', max_digits=10, null=True, verbose_name='Base Charge (₹)')),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
    ]
