# Generated by Django 5.2.6 on 2025-09-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amenities', '0002_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='related_services',
            field=models.ManyToManyField(blank=True, help_text='Services associated with this amenity', related_name='amenities', to='service.service', verbose_name='Related Services'),
        ),
    ]
